# Generated by Django 4.1.2 on 2022-10-15 22:30

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('note2_t', '0002_notes_delete_quillpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
