# Generated by Django 4.1.2 on 2022-10-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note2_t', '0004_alter_notes_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
    ]
